name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create deployment directory
      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp index.html style.css *.png deploy/

      # Simple API key replacement
      - name: Replace API key
        run: |
          # Create a modified script file
          cat script.js | sed "s/'PLACEHOLDER'/'${{ secrets.OPENWEATHER_API_KEY }}'/g" > deploy/script.js
          
      # Verify the script
      - name: Verify script
        run: |
          echo "Checking for PLACEHOLDER in script"
          ! grep -q "PLACEHOLDER" deploy/script.js || (echo "ERROR: PLACEHOLDER still found" && exit 1)
          echo "No PLACEHOLDER found, verification successful"
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages