name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create deployment directory
      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp style.css *.png deploy/

      # Create a version of the script with a different name
      - name: Create weather-app.js with API key
        run: |
          cat script.js | sed "s/'PLACEHOLDER'/'${{ secrets.OPENWEATHER_API_KEY }}'/g" > deploy/weather-app.js
          echo "const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';" > deploy/weather-app.js.new
          tail -n +33 script.js >> deploy/weather-app.js.new
          mv deploy/weather-app.js.new deploy/weather-app.js

      # Create modified index.html that uses the new script name
      - name: Create modified index.html
        run: |
          cat index.html | sed 's/<script src="\.\/script\.js"><\/script>/<script src="\.\/weather-app\.js"><\/script>/g' > deploy/index.html

      # Verify the script
      - name: Verify script
        run: |
          echo "Checking for PLACEHOLDER in weather-app.js"
          if grep -q "PLACEHOLDER" deploy/weather-app.js; then
            echo "ERROR: PLACEHOLDER still found in weather-app.js"
            exit 1
          fi
          echo "No PLACEHOLDER found, verification successful"
          
          # Check if index.html references the new script
          if grep -q "weather-app.js" deploy/index.html; then
            echo "SUCCESS: index.html now references weather-app.js"
          else
            echo "ERROR: index.html does not reference weather-app.js"
            exit 1
          fi
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages