# name: Deploy with API Key

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
      
#       - name: Debug - List files
#         run: ls -la
        
#       - name: Debug - Find JS files
#         run: find . -name "*.js"
      
        
#       - name: Replace API Key
#         env:
#           OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
#         run: find . -name "*.js" -exec sed -i "s/PLACEHOLDER/${OPENWEATHER_API_KEY}/g" {} +



#       # - name: Replace API Key
#       #   env:
#       #     OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
#       #   run: sed -i "s/PLACEHOLDER/${OPENWEATHER_API_KEY}/g"
          
#       - name: Debug - Verify Replacement
#         run: |
#           find . -name "*.js" -type f -exec grep -l "API_KEY" {} \; | xargs cat
          
#       - name: Debug Secret Access
#         env:
#           OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
#         if: env.OPENWEATHER_API_KEY && env.OPENWEATHER_API_KEY != ''
#         run: echo "Secret is set"

#       - name: Deploy to GitHub Pages
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           folder: .
#           branch: gh-pages
#           token: ${{ secrets.GITHUB_TOKEN }}


name: Deploy with API Key

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug - List files
        run: ls -la
        
      - name: Debug - Find JS files
        run: find . -name "*.js"
        
      - name: Replace API Key
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: find . -name "*.js" -exec sed -i "s/PLACEHOLDER/${OPENWEATHER_API_KEY}/g" {} +
          
      - name: Debug - Verify Replacement
        run: |
          find . -name "*.js" -type f -exec grep -l "API_KEY" {} \; | xargs cat
          
      - name: Debug Secret Access
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        if: env.OPENWEATHER_API_KEY && env.OPENWEATHER_API_KEY != ''
        run: echo "Secret is set"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4

        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://<YOUR_PAT>@github.com/konmez/weather-panel.git
          git checkout -B gh-pages
          git add .
          git commit -m "Deploying to gh-pages from GitHub Actions"
          git push origin gh-pages --force
      env:
        YOUR_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}      
        with:
          folder: .
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

