name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Update API key in script.js
      - name: Update API key in script.js
        run: |
          # First, check if the API key is available
          if [ -z "${{ secrets.OPENWEATHER_API_KEY }}" ]; then
            echo "ERROR: OPENWEATHER_API_KEY is not set in repository secrets"
            exit 1
          fi
          
          # Update API key in script.js
          sed -i "s/PLACEHOLDER/${{ secrets.OPENWEATHER_API_KEY }}/g" script.js
          
      # Add cache-busting to HTML
      - name: Add cache-busting to HTML
        run: |
          # Generate a timestamp for cache busting
          TIMESTAMP=$(date +%s)
          
          # Backup original HTML
          cp index.html index.html.bak
          
          # Update script reference with cache-busting parameter
          sed -i "s|<script src=\"./script.js\"></script>|<script src=\"./script.js?v=$TIMESTAMP\"></script>|" index.html
          
          # Verify changes
          echo "Updated script tag in HTML:"
          grep -n "script.js" index.html
          
      # Verify the API key was properly inserted
      - name: Verify API key
        run: |
          echo "Checking for PLACEHOLDER in script.js:"
          if grep -q "PLACEHOLDER" script.js; then
            echo "ERROR: PLACEHOLDER still found in script.js!"
            exit 1
          else
            echo "SUCCESS: No PLACEHOLDERs found in script.js"
          fi
          
          # Check for the API key (masked for security)
          echo "Checking for API_KEY with actual value:"
          if grep -q "${{ secrets.OPENWEATHER_API_KEY }}" script.js; then
            echo "SUCCESS: API key properly inserted"
          else
            echo "ERROR: API key not found in script.js"
            exit 1
          fi
        
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          