name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Direct edit of script.js to replace API key
      - name: Update API key in script.js
        run: |
          # Make a backup of the original script
          cp script.js script.js.bak
          
          # First, check if the API key is available
          if [ -z "${{ secrets.OPENWEATHER_API_KEY }}" ]; then
            echo "ERROR: OPENWEATHER_API_KEY is not set in repository secrets"
            exit 1
          fi
          
          # Look for any pattern of API_KEY in the file and update it
          if grep -q "API_KEY" script.js; then
            echo "Found API_KEY references in script.js, updating..."
            
            # Replace different forms of API_KEY definitions
            # Note: This uses direct string replacement, not regex
            sed -i "s/\/\/const API_KEY = 'PLACEHOLDER';/const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';/" script.js
            sed -i "s/\/\/let API_KEY = 'PLACEHOLDER';/const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';/" script.js
            sed -i "s/const API_KEY = 'PLACEHOLDER';/const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';/" script.js
            sed -i "s/const API_KEY = \"\";/const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';/" script.js
            
            # If none of the above patterns match, add the API key definition
            if ! grep -q "const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}'" script.js; then
              echo "API key pattern not found. Adding API key definition..."
              sed -i "/const WEATHER_BASE_URL/a const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';" script.js
            fi
          else
            echo "No API_KEY references found. Adding API key definition..."
            sed -i "/const WEATHER_BASE_URL/a const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';" script.js
          fi
      
      # Verify the API key was properly inserted
      - name: Verify API key
        run: |
          echo "Checking API_KEY in script.js:"
          grep -n "API_KEY" script.js || echo "No API_KEY found!"
          
          # Count occurrences to make sure we don't have duplicates
          API_KEY_COUNT=$(grep -c "API_KEY" script.js || echo 0)
          echo "Number of API_KEY occurrences: $API_KEY_COUNT"
          
          # Final verification
          if grep -q "const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}'" script.js; then
            echo "SUCCESS: API key properly inserted"
          else
            echo "ERROR: API key not found in expected format"
            echo "Diff between original and modified script:"
            diff script.js.bak script.js || true
            exit 1
          fi
        
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          