name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Debug the script file contents
      - name: Debug script file
        run: |
          echo "Looking for PLACEHOLDER in script.js:"
          grep -n "PLACEHOLDER" script.js || echo "Not found with grep"
          
          # Check for exact API_KEY declaration pattern
          echo "Checking for API_KEY declaration:"
          grep -n "API_KEY" script.js

      # Create deployment directory
      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp style.css *.png deploy/

      # Create a completely new script with API key explicitly defined
      - name: Create weather-app.js with API key
        run: |
          # Create a completely new file with the API key at the top
          echo "// Weather app script - Generated $(date)" > deploy/weather-app.js
          echo "// API key for OpenWeatherMap" >> deploy/weather-app.js
          echo "const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';" >> deploy/weather-app.js
          
          # Extract the rest of the script but skip any API_KEY declarations
          cat script.js | grep -v "API_KEY" | grep -v "PLACEHOLDER" >> deploy/weather-app.js

      # Create modified index.html
      - name: Create modified index.html
        run: |
          # Create modified index.html with new script reference
          sed 's|<script src="./script.js">|<script src="./weather-app.js">|g' index.html > deploy/index.html

      # Verify the files
      - name: Verify files
        run: |
          echo "Checking for PLACEHOLDER in weather-app.js"
          if grep -q "PLACEHOLDER" deploy/weather-app.js; then
            echo "ERROR: PLACEHOLDER still found in weather-app.js"
            cat deploy/weather-app.js | grep -n "PLACEHOLDER"
            exit 1
          fi
          echo "No PLACEHOLDER found, verification successful"
          
          # Check if index.html references the new script
          if grep -q "weather-app.js" deploy/index.html; then
            echo "SUCCESS: index.html now references weather-app.js"
          else
            echo "ERROR: index.html does not reference weather-app.js"
            exit 1
          fi
          
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages