name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create deployment directory
      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp index.html style.css *.png deploy/
        
      # Create script with exact pattern match replacement
      - name: Create script with correct API key
        run: |
          # Use exact pattern matching for replacement
          sed "s/const API_KEY = 'PLACEHOLDER'; \/\/ Get your own API key from https:\/\/openweathermap.org\//const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}'; \/\/ API key inserted by GitHub Actions/g" script.js > deploy/script.js
          
          # Verify replacement
          echo "Checking if the replacement was successful:"
          if grep -q "PLACEHOLDER" deploy/script.js; then
            echo "ERROR: PLACEHOLDER still found in script.js"
            
            # Try alternative approach with perl
            echo "Trying alternative approach with perl..."
            perl -pe "s/const API_KEY = 'PLACEHOLDER'; \/\/ Get your own API key from https:\/\/openweathermap.org\//const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}'; \/\/ API key inserted by GitHub Actions/g" script.js > deploy/script.js.new
            mv deploy/script.js.new deploy/script.js
            
            # Check again
            if grep -q "PLACEHOLDER" deploy/script.js; then
              echo "ERROR: Both approaches failed. Manual intervention needed."
              
              # Create a new script file from scratch
              cat > deploy/script.js.new << EOL
// This file was generated by GitHub Actions
// Original file: script.js
// Generated on: $(date)

// Set API key first - IMPORTANT
const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';

$(cat script.js | grep -v "API_KEY" | grep -v "PLACEHOLDER")
EOL
              mv deploy/script.js.new deploy/script.js
            fi
          else
            echo "SUCCESS: PLACEHOLDER successfully replaced"
          fi
          
      # Verify final script
      - name: Verify final script
        run: |
          echo "Checking for PLACEHOLDER in final script:"
          if grep -q "PLACEHOLDER" deploy/script.js; then
            echo "ERROR: PLACEHOLDER still found in final script"
            exit 1
          else
            echo "SUCCESS: No PLACEHOLDER found in final script"
          fi
          
          echo "Checking for API key in final script:"
          if grep -q "API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}'" deploy/script.js; then
            echo "SUCCESS: API key correctly inserted"
          else
            echo "ERROR: API key not found in expected format"
            exit 1
          fi
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages