name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up API key
      #   run: |
      #     cat paste.txt | sed "s/const API_KEY = 'PLACEHOLDER';/const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';/" > weather.js
      #     mv  weather.js config.js


      - name: Create script.js with embedded API key
        run: |
          # Replace the API key placeholder directly in the script
          cat script.js | sed "s|//let API_KEY = 'PLACEHOLDER';|const API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';|" > script.js
          echo "Created script.js with embedded API key"

      # - name: Create config.js with API key
      #   run: |
      #     echo "// API key for OpenWeatherMap" > config.js
      #     echo "let API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';" >> config.js
      
      - name: List files
        run: |
          echo "Files in repository:"
          ls -la
      
      # - name: list config.js
      #   run: |
      #     echo "Contents of config.js:"
      #     cat config.js
        


      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .         # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to