name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Debug the API key (without showing it)
      - name: Debug API key
        run: |
          echo "API key exists: ${{ secrets.OPENWEATHER_API_KEY != '' }}"
          echo "API key length: ${#OPENWEATHER_API_KEY}"
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

      # Create script.js with the correct API key
      - name: Create script.js with API key
        run: |
          # Make sure we're starting with a clean script
          cat paste.txt > script.js
          
          # Important: Check if API key is actually available
          if [ -z "${{ secrets.OPENWEATHER_API_KEY }}" ]; then
            echo "ERROR: OPENWEATHER_API_KEY secret is empty or not set!"
            exit 1
          fi
          
          # Replace all instances of API_KEY definitions with the correct one
          sed -i 's|//const API_KEY = .*|const API_KEY = "${{ secrets.OPENWEATHER_API_KEY }}";|g' script.js
          sed -i 's|//let API_KEY = .*|const API_KEY = "${{ secrets.OPENWEATHER_API_KEY }}";|g' script.js
          sed -i 's|const API_KEY = .*|const API_KEY = "${{ secrets.OPENWEATHER_API_KEY }}";|g' script.js
          sed -i 's|let API_KEY = .*|const API_KEY = "${{ secrets.OPENWEATHER_API_KEY }}";|g' script.js
          
      # Verify the API key replacement
      - name: Verify API key insertion
        run: |
          echo "Lines with API_KEY in script.js:"
          grep -n "API_KEY" script.js | grep -v "grep" | head -5
          
          # Check if API_KEY is properly defined with a non-empty value
          if grep -q 'API_KEY = "";' script.js; then
            echo "ERROR: API_KEY is empty in script.js!"
            exit 1
          fi
          
          if grep -q 'API_KEY = "${{ secrets.OPENWEATHER_API_KEY }}";' script.js; then
            echo "SUCCESS: API_KEY template is present, will be replaced during deployment"
          else
            echo "ERROR: API_KEY template not found in script.js!"
            exit 1
          fi
        
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          